name: first work demo
on: 
  workflow_dispatch
jobs:
  first-job:
   runs-on: ubuntu-latest
   steps: 
    - name: print hello
      run: |
       curl -k -w -L'\\n%{response_code}' --header 'Content-Disposition: file;' -O http://www.java2s.com/Code/JarDownload/java-remote/java-remote-control-with-source.jar.zip
       ls -lrt
       if [ $response_code == "200" ]
       (
         echo "Download done"
       )
       else (
         echo "error"
       )
