name: Second Job
on:
  workflow_dispatch:
jobs:
  second_flow:
    runs-on: ubuntu-latest
    steps:
      - name: print hello there
        run: |
            echo "Hello There"
            echo "How are you?"
