name: Second Job
on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: number
        description: provide build number
jobs:
  second_flow:
    runs-on: ubuntu-latest
    steps:
      - name: print hello there
        run: |
            echo "Hello There"
            echo "How are you?"
      - name: runing curl command
        run: | 
            df -h
            which curl
            echo "${{ inputs.build_id }}"
            
